version: 2

publications:
  - url: https://nuget.org/packages/LaunchDarkly.Logging
    description: NuGet

jobs:
  - docker: {}
    template:
      name: dotnet-linux
    env:
      LD_RELEASE_TEST_TARGET_FRAMEWORK: net50
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netcoreapp2.1 # so the docs will include Logs.CoreLogging

branches:
  - name: main
  - name: 1.x

documentation:
  title: LaunchDarkly Logging API for .NET
  gitHubPages: true
